name: Deploy Frontend to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build frontend
        uses: actions/setup-node@v3

      - run: |
          echo "${{ secrets.BACKEND_IP }}" > .env  

      - run: |
          npm install
          npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: cloud-temp-400907
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_FRONTEND_KEY }}
          export_default_credentials: true


      - name: Deploy to GCS
        run: |
          gsutil cp -r ./* gs://cb-website
        working-directory: ./dist
