name: Deploy Frontend to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Goggle Cloud
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_FRONTEND_KEY }}
          project_id: cloud-temp-400907

      - name: Deploy to GCS
        run: |
          gsutil cp -r ./* gs://frontend-bucket-ccc-2023-group
        working-directory: ./

      - name: Clean Up
        run: |
          gsutil cp -r ./* gs://frontend-bucket-ccc-2023-group
        working-directory: ./
